### ISSUE TITLE
Write folder does not have the content from previous games

### ISSUE THREAD

**Issue by MicroDK** [Games-and-Simulations/sc-docker#25]
**expected behaviour**
When using the --read_overwrite option, at start of game, content of the read folder should be copied to the game's write folder.

**actual behaviour**
When using the --read_overwrite option the game's write folder is empty. Some bots will use the content from previous games' write folder e.g adding lines to an enemy text file for updating opening learning.

**Comment by certicky** [comment]
I think this is not what's supposed to happen. Check out what the tournaments do with these folders: https://sscaitournament.com/index.php?action=rules 

"After every match, the contents of the write directory is copied to the read directory with auto-overwrite."

**Comment by MicroDK** [comment]
Docker scbw creates games folders with IDs within the write folder eg:
drwxr-xr-x  3 micky  staff  102 Feb  3 12:36 GAME_D2153FAB_1
drwxr-xr-x  3 micky  staff  102 Feb  3 12:25 GAME_E475ABD3_1
drwxr-xr-x  2 micky  staff   68 Jan 20 15:45 GAME_F4D16A06_1

I think it should not create these game folders, but just save the write files directly into the write folder and then copy the contents of the write folder to the read folder.

**Comment by michalsustr** [comment]
> at start of game, content of the read folder should be copied to the game's write folder.
I think you meant the other way, right? `write` -> `read`, not the other way around.

The subfolders are intentional design, there can be multiple games running at the same times, e.g. bot `A` against bots `B`, `C`, ... , `Z` and this step is needed to prevent potential file corruptions.

Though I agree this should be documented, when I find some more time I will do that. Or you can create PR with docs :) 

Closing for now.
