### ISSUE TITLE
Feature Request --map random flag

### ISSUE THREAD

**Issue by RothNath** [Games-and-Simulations/sc-docker#74]
When running large numbers of games it would be helpful to be able to pick a random map from the pool instead of needed to use a custom python script ontop. There may be other preferred ways of doing the syntax, but I think it would see quite a bit of use. 

something like : --map -r

in use example : scbw.play --bots "Purplewave" "Krasi0" --auto_launch --game_speed 0 --map -r

Thank you again for the work put into this project.

**Comment by michalsustr** [comment]
Thank you for appreciative words :)

This sort of functionality can be done by external scripts, I want to keep `sc-docker` as simple as possible.

I have a set of scripts that do this here: https://github.com/Games-and-Simulations/sc-mq
but it's tested on linux only and at the moment I don't want to make support for it, so that's why it wasn't public. 

I just published it, but expect some possible pain setting it up :)
